let stockProductos = [
    {id: 1, nombre: "ZAPATILLAS ADIDAS", tipo: "zapatilla", cantidad: 1, desc:"", precio: 40000, talle: "L", img: './img/adidas-dame-certified.jpg'},
    {id: 2, nombre: "ZAPATILLAS ASICS", tipo: "zapatilla", cantidad: 1, desc: "", precio: 32000, talle: "L", img: './img/AsicsBackhand.jpg'},
    {id: 3, nombre: "CALZA VOLEY", tipo: "calza", cantidad: 1, desc: "", precio: 2200, talle: "M", img: './img/CALZA.jpg'},
    {id: 4, nombre: "CAMISETA LOSER", tipo: "camiseta", cantidad: 1, desc: "", precio: 4200, talle: "M", img: './img/camisetaloser.png'},
    {id: 5, nombre: "CAMISETA ARGENTINA", tipo: "camiseta", cantidad: 1, desc: "", precio: 13000, talle: "S", img: './img/CamisetaSeleccion.png'},
    {id: 6, nombre: "CAMISETA VOLLEYBALL WORLD", tipo: "camiseta", cantidad: 1, desc: "", precio: 7000, talle: "S", img: './img/CamisetaVW.png'},
    {id: 7, nombre: "CAMISETA DE CECCO", tipo: "camiseta", cantidad: 1, desc: "", precio: 4200, talle: "L", img: './img/DeCecco.png'},
    {id: 8, nombre: "ZAPATILLAS ASICS", tipo: "zapatilla", cantidad: 1, desc: "", precio: 32000, talle: "L", img: './img/GELREBOUND.jpg'},
    {id: 9, nombre: "GEMELERAS SOX", tipo: "gemelera", cantidad: 1, desc: "", precio: 2500, talle: "M", img: './img/gemeleras.jpg'},
    {id: 10, nombre: "GORRA", tipo: "gorra", cantidad: 1, desc: "", precio: 1800, talle: "M", img: './img/gorra.jpg'},
    {id: 11, nombre: "REMERA MADE OF VOLLEYBALL", tipo: "remera", cantidad: 1, desc: "", precio: 2450, talle: "S", img: './img/MadeOfVolleyREMERA.png'},
    {id: 12, nombre: "ZAPATILLAS ASICS", tipo: "zapatilla", cantidad: 1, desc: "", precio: 32000, talle: "S", img: './img/GREBOUND-SEA.jpg'},
    {id: 13, nombre: "GEMELERAS SONDER", tipo: "gemelera", cantidad: 1, desc: "", precio: 1980, talle: "L", img: './img/manga.jpg'},
    {id: 14, nombre: "MEDIAS SOX ARGENTINA", tipo: "media", cantidad: 1, desc: "", precio: 1240, talle: "S", img: './img/medias.jpg'},
    {id: 15, nombre: "MEDIAS SOX ANTIDESLIZANTE", tipo: "media", cantidad: 1, desc: "", precio: 1370, talle: "L", img: './img/MediasSOX.jpg'},
    {id: 16, nombre: "MUSCULOSA ARGENTINA", tipo: "camiseta", cantidad: 1, desc: "", precio: 6000, talle: "S", img: './img/MUSCULOSA-ARG.jpg'},
    {id: 17, nombre: "MUSCULOSA SONDER", tipo: "camiseta", cantidad: 1, desc:"", precio: 4700, talle: "S", img: './img/MusculosaBeach.jpg'},
    {id: 18, nombre: "PELOTA NASSAU", tipo: "pelota", cantidad: 1, desc: "", precio: 11400, talle: "", img: './img/NASSAU-PELOTA.jpg'},
    {id: 19, nombre: "PELOTA KAGIVA ARGENTINA", tipo: "pelota", cantidad: 1, desc: "", precio: 9800, talle: "", img: './img/PelotaKagiva.png'},
    {id: 20, nombre: "RODILLERAS NIKE", tipo: "rodillera", cantidad: 1, desc: "", precio: 18000, talle: "L", img: './img/Rodilleras.jpg'},
    {id: 21, nombre: "RODILLERAS UMBRO", tipo: "rodillera", cantidad: 1, desc: "", precio: 9700, talle: "M", img: './img/RodillerasUmbro.jpg'},
    {id: 22, nombre: "CALZA VOLEY", tipo: "calza", cantidad: 1, desc: "", precio: 2700, talle: "M", img: './img/CALZA.jpg'},
    {id: 23, nombre: "ZAPATILLAS ASICS", tipo: "zapatilla", cantidad: 1, desc: "", precio: 32000, talle: "S", img: './img/GELREBOUND.jpg'},
    {id: 24, nombre: "CAMISETA DE CECCO", tipo: "camiseta", cantidad: 1, desc: "", precio: 4800, talle: "S", img: './img/DeCecco.png'},
]